version: "2"
linters:
  # only enable the linters listed below
  default: none
  enable:
    - asciicheck
    # ensure that http response bodies are closed
    - bodyclose
    - copyloopvar
    # make sure all errors returned by functions are handled
    - errcheck
    # examine code and report suspicious constructs, such as Printf calls whose
    # arguments do not align with the format string
    - govet
    # consistent imports
    - importas
    # detect when assignments to existing variables are not used
    - ineffassign
    - nolintlint
    # make sure names and comments are used according to the conventions
    - revive
    # run static analysis and find errors
    - staticcheck
    # find unused variables, functions, structs, types, etc.
    - unused
  exclusions:
    rules:
      - path: (.+)\.go$
        text: exported (function|method|var|type|const) .* should have comment or be unexported
      - path: (.+)\.go$
        text: don't use ALL_CAPS in Go names; use CamelCase
      - path: (.+)\.go$
        text: "package-comments: should have a package comment"
      - path: (.+)\.go$
        text: "redefines-builtin-id:"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
